(********************************************************************************

 Examples of Unital Magmoids

 Contents:
 1. The unital magmoid with a non-intermediate [lt_iso]

 Author: B. Szilvasy
 April 2026

 ********************************************************************************)

Require Import UniMath.Foundations.All.
Require Import UniMath.MoreFoundations.All.

Require Import UniMath.Combinatorics.StandardFiniteSets.
Require Import UniMath.CategoryTheory.Core.Categories.
Require Import UniMath.CategoryTheory.Core.Isos.

Require Import UniMath.CategoryTheory.Nonassociative.UnitalMagmoids.Core.
Require Import UniMath.CategoryTheory.Nonassociative.UnitalMagmoids.Isos.

Local Open Scope cat.
Local Open Scope stn.

(** 1. The unital magmoid with a non-intermediate [lt_iso]

 There is a linear-and-thunkable isomorphism which is not intermediate
 ([exists_non_intermediate_lt_iso]).  An example is found in a simple unital
 magmoid generated by four objects and four morphisms, as depicted in the
 following diagram. The morphisms p and q are assumed to be linear and thunkable
 inverses to each other, but no other constraints are placed.  This makes p (and
 dually q) a linear-and-thunkable isomorphism which is not intermediate.

    a -f-> b -g-> c
          | ^
          p |
          | q
          v |
           d

 The unital magmoid is realized (see [lini_mor]) by setting:
 - [a --> b], [b --> c], [b --> d], [d --> b], and all [x --> x] to [unit];
 - [a --> c] to [bool];
 - all other hom-sets to [empty].

 *)

(* The unital magmoid is named "lini" after this section heading. *)
Section lt_iso_not_intermediate.
  Definition lini_ob : UU := ⟦4⟧.

  (* Dependent eliminator for [lini_ob]. *)
  Definition lini_rec₀
    (P : lini_ob -> UU)
    (a : ∏ H, P (0,,H)) (b : ∏ H, P (1,,H)) (c : ∏ H, P (2,,H)) (d : ∏ H, P (3,,H))
    : ∏ (x : lini_ob), P x.
  Proof.
    intro x; induction x as [n Hn].
    do 4 try induction n as [|n _].
    - exact (a Hn).
    - exact (b Hn).
    - exact (c Hn).
    - exact (d Hn).
    - apply fromempty, nopathsfalsetotrue, Hn.
  Defined.

  (* Non-dependent eliminator for [lini_ob]. *)
  Definition lini_rec
    (P : UU) (a : P) (b : P) (c : P) (d : P)
    : ∏ (x : lini_ob), P.
  Proof.
    apply lini_rec₀.
    all: intro Hn.
    - exact a.
    - exact b.
    - exact c.
    - exact d.
  Defined.

  (* Alternative dependent eliminator for [lini_ob].
     This still computes definitionally, though [cbn] is slow at it. *)
  Definition lini_ind
    (P : lini_ob -> UU)
    (a : P (●0)) (b : P (●1)) (c : P (●2)) (d : P (●3))
    : ∏ (x : lini_ob), P x.
  Proof.
    apply lini_rec₀.
    all: intro Hn;
      refine (transportf (λ p, P (_,, p))
                (proofirrelevance _ (isasetbool _ _) _ Hn)
                _).
    - exact a.
    - exact b.
    - exact c.
    - exact d.
  Defined.
  Goal (lini_ind (λ _, nat) 0 1 2 3 (●0) = 0). reflexivity. Qed.
  Goal (lini_ind (λ _, nat) 0 1 2 3 (●1) = 1). reflexivity. Qed.
  Goal (lini_ind (λ _, nat) 0 1 2 3 (●2) = 2). reflexivity. Qed.
  Goal (lini_ind (λ _, nat) 0 1 2 3 (●3) = 3). reflexivity. Qed.

  Definition lini_mor (x y : lini_ob) : UU
    := lini_rec UU        (* a     b     c     d *)
         ((* a *)lini_rec UU unit  unit  bool  unit  y)
         ((* b *)lini_rec UU empty unit  unit  unit  y)
         ((* c *)lini_rec UU empty empty unit  empty y)
         ((* d *)lini_rec UU empty unit  unit  unit  y)
         x.

  Definition lini_comp {x y z : lini_ob}
    (h : lini_mor x y) (k : lini_mor y z)
    : lini_mor x z.
  Proof.
    induction x using lini_rec₀;
      induction y using lini_rec₀;
      induction z using lini_rec₀.
    all: try contradiction.
    all: try exact tt.
    - exact k. (* id a · k = k *)
    - exact false. (* f · g *)
    - exact h. (* h · id c = h *)
    - exact true. (* (f · p) · (q · g) *)
  Defined.

  Definition lini_id (x : lini_ob) : lini_mor x x.
  Proof.
    induction x using lini_rec₀; exact tt.
  Defined.

  Definition lini_precategory_ob_mor : precategory_ob_mor
    := make_precategory_ob_mor lini_ob lini_mor.
  Definition lini_precategory_data : precategory_data
    := make_precategory_data lini_precategory_ob_mor
         lini_id (@lini_comp).

  Definition is_unital_premagmoid_lini
    : is_unital_premagmoid lini_precategory_data.
  Proof.
    split; intros x y f;
      induction x using lini_rec₀;
      induction y using lini_rec₀.
    all: try contradiction.
    all: try reflexivity.
    all: now induction f.
  Qed.

  Definition lini_premagmoid : unital_premagmoid
    := make_unital_premagmoid _ is_unital_premagmoid_lini.

  Definition has_homsets_lini_precategory
    : has_homsets lini_precategory_data.
  Proof.
    intros x y; induction x using lini_rec₀; induction y using lini_rec₀;
      (exact isasetunit || exact isasetempty || exact isasetbool).
  Qed.

  Definition lini : unital_magmoid
    := make_unital_magmoid lini_premagmoid has_homsets_lini_precategory.

  Definition lini_a : lini := ●0.
  Definition lini_b : lini := ●1.
  Definition lini_c : lini := ●2.
  Definition lini_d : lini := ●3.
  Definition lini_f : lini_a --> lini_b := tt.
  Definition lini_g : lini_b --> lini_c := tt.
  Definition lini_p : lini_b --> lini_d := tt.
  Definition lini_q : lini_d --> lini_b := tt.

  Lemma is_inverse_in_precat_lini_p_q : is_inverse_in_precat lini_p lini_q.
  Proof. now split. Qed.

  Lemma is_linear_and_thunkable_lini_p : is_linear_and_thunkable lini_p.
  Proof.
    split; intros x y h k; induction x using lini_rec₀; induction y using lini_rec₀.
    all: try contradiction.
    all: reflexivity.
  Qed.

  Lemma is_linear_and_thunkable_lini_q : is_linear_and_thunkable lini_q.
  Proof.
    split; intros x y h k; induction x using lini_rec₀; induction y using lini_rec₀.
    all: try contradiction.
    all: reflexivity.
  Qed.

  Lemma is_lt_iso_lini_p : is_lt_iso lini_p.
  Proof.
    use make_is_lt_iso'.
    - exact is_linear_and_thunkable_lini_p.
    - exact lini_q.
    - exact is_linear_and_thunkable_lini_q.
    - exact is_inverse_in_precat_lini_p_q.
  Defined.

  Definition lini_p' : lt_iso lini_b lini_d := make_lt_iso lini_p is_lt_iso_lini_p.

  Lemma is_not_intermediate_lini_p' : ¬is_intermediate lini_p'.
  Proof.
    intro H.
    assert (H' := H _ _ lini_f (lini_q · lini_g)).
    exact (nopathsfalsetotrue H').
  Qed.

  Corollary exists_non_intermediate_lt_iso
    : ∑ (M : unital_magmoid) (a b : M) (p : lt_iso a b), ¬is_intermediate p.
  Proof.
    exact (_,,_,,_,,lini_p',,is_not_intermediate_lini_p').
  Defined.

  Corollary lt_iso_does_not_imply_intermediate
    : ¬(∏ (M : unital_magmoid) (a b : M) (p : lt_iso a b), is_intermediate p).
  Proof.
    intro H.
    refine (pr2 (pr222 exists_non_intermediate_lt_iso) _).
    apply H.
  Qed.

End lt_iso_not_intermediate.
